export const SCREEN = {
    'INIT': 0,
    'PLAYER_SELECT': 1,
    'SKILLS_SELECT': 2
}

export const SPEC_ICON_MAP = {
    "DeathKnight-Blood": "spell_deathknight_bloodpresence",
    "DeathKnight-Frost": "spell_deathknight_frostpresence",
    "DeathKnight-Unholy": "spell_deathknight_unholypresence",
    "DemonHunter-Havoc": "ability_demonhunter_specdps",
    "DemonHunter-Vengeance": "ability_demonhunter_spectank",
    "Druid-Balance": "spell_nature_starfall",
    "Druid-Feral": "ability_druid_catform",
    "Druid-Guardian": "ability_racial_bearform",
    "Druid-Restoration": "spell_nature_healingtouch",
    "Hunter-BeastMastery": "ability_hunter_bestialdiscipline",
    "Hunter-Marksmanship": "ability_hunter_focusedaim",
    "Hunter-Survival": "ability_hunter_camouflage",
    "Mage-Arcane": "spell_holy_magicalsentry",
    "Mage-Fire": "spell_fire_firebolt02",
    "Mage-Frost": "spell_frost_frostbolt02",
    "Monk-Brewmaster": "spell_monk_brewmaster_spec",
    "Monk-Mistweaver": "spell_monk_mistweaver_spec",
    "Monk-Windwalker": "spell_monk_windwalker_spec",
    "Paladin-Holy": "spell_holy_holybolt",
    "Paladin-Protection": "spell_holy_devotionaura",
    "Paladin-Retribution": "spell_holy_auraoflight",
    "Priest-Discipline": "spell_holy_powerwordshield",
    "Priest-Holy": "spell_holy_guardianspirit",
    "Priest-Shadow": "spell_shadow_shadowwordpain",
    "Rogue-Assassination": "ability_rogue_deadlybrew",
    "Rogue-Outlaw": "ability_rogue_waylay",
    "Rogue-Subtlety": "ability_stealth",
    "Shaman-Elemental": "spell_nature_lightning",
    "Shaman-Enhancement": "spell_shaman_improvedstormstrike",
    "Shaman-Restoration": "spell_nature_magicimmunity",
    "Warlock-Affliction": "spell_shadow_deathcoil",
    "Warlock-Demonology": "spell_shadow_metamorphosis",
    "Warlock-Destruction": "spell_shadow_rainoffire",
    "Warrior-Arms": "ability_warrior_savageblow",
    "Warrior-Fury": "ability_warrior_innerrage",
    "Warrior-Protection": "ability_warrior_defensivestance"
}